multi_param:
  dirpath: .
  filename: run_3000.nc
  num_runs: 3000
  processors: 10
  C_total_min: #0.0001
  C_total_max: #0.005
  Cmin: 0.00001
  Cmax: 0.005
  Umin: 0.1
  Umax: 10.0
  hmin: 0.1
  hmax: 10.0
  rmin: # None
  rmax: # None
  endmin: 1800 # 30 min
  endmax: 864000 # 10 days
  saltmin: 
  saltmax: 
  Cfmin: 0.004
  Cfmax: 0.004
  pmin: 0.1
  pmax: 0.1
  alpha_4eqmin: 0.6
  alpha_4eqmax: 0.6
  r0min: 2.0
  r0max: 2.0
  det_coef_min: 3.05
  det_coef_max: 3.05
  repeat: 1
  timelimit: # None
  flow_type: continuous
  is_suspended_sediment: [False, True]

grid_param:
  grid_file: basin_l16_w8_dx100m.npy
  flume_length: 
  flume_width: 
  spacing: 100
  slope_outside:
  slope_inside: 
  slope_basin: 
  slope_basin_break: 
  canyon_basin_break:
  canyon_center: 
  canyon_half_width:
  canyon:
  noise:

boundary_condition:
  top_edge: fixed_value
  bottom_edge: fixed_gradient
  left_edge: fixed_gradient
  right_edge: fixed_gradient

inlet_condition:
  inlet_edge: 
  inlet_width: 1000
  h_ini: 
  C_ini: 
  U_ini: 

model_param:
  h_init: 0.0
  Ch_w: 10.0e-10
  h_w: 0.01
  alpha: 0.1
  Cf: 0.004
  g: 9.81
  R: 1.65
  Ds: 
    - 2.0e-5 # silt
    - 3.0e-6 # clay
  lambda_p: 0.4
  r0: 2.0
  nu: 1.010e-6
  kappa: 0.05
  nu_a: 0.75
  implicit_num: 300
  implicit_threshold: 1.0e-12
  C_init: 0.0
  gamma: 0.35
  la: 0.01
  water_entrainment: True
  water_detrainment: True
  detrainment_coef: 3.05
  suspension: True
  sed_entrainment_func: GP1991field
  no_erosion: False
  bedload_transport: False
  model: 4eq
  salt: False
  alpha_4eq: 0.6
  karman: 0.4
  p: 0.1
  multi_flow: True