grid_param:
  grid_file: 
  flume_length: 1.0
  flume_width: 1.0
  spacing: 0.05
  slope_outside: 0.1
  slope_inside: 0.1
  slope_basin: 0.1
  slope_basin_break: 0.1
  canyon_basin_break: 0.1
  canyon_center: 0.1
  canyon_half_width: 0.1
  canyon: 0.1
  noise: 0.1

inlet_condition:
  inlet_edge:
  inlet_width: 0.3
  h_ini: 1.0
  C_ini: 
        - 0.0025
        - 0.0025
        - 0.0025
        - 0.0025
  U_ini: 1.0

boundary_condition:
  top_edge: fixed_value
  bottom_edge: fixed_gradient
  left_edge: fixed_gradient
  right_edge: fixed_gradient

model_param:
  h_init: 0.0
  Ch_w: 10.0e-10
  h_w: 0.001
  alpha: 0.08
  Cf: 0.004
  g: 9.81
  R: 1.65
  Ds: 
    - 1.5e-4 # fine sand
    - 1.0e-4 # very fine sand
    - 2.0e-5 # silt
    - 3.0e-6 # clay
  lambda_p: 0.4
  r0: 2.0
  nu: 1.010e-6
  kappa: 0.05
  nu_a: 0.75
  implicit_num: 500
  implicit_threshold: 1.0e-12
  C_init: 0.0
  gamma: 0.35
  la: 0.003
  water_entrainment: True
  water_detrainment: True
  detrainment_coef: 1.0
  suspension: True
  sed_entrainment_func: GP1991exp
  no_erosion: False
  bedload_transport: False
  model: 4eq
  salt: False
  alpha_4eq: 0.6
  karman: 0.4
  p: 1.0
  flow_type: continuous
  one_way_nesting: False
  two_way_nesting: False