h_init: 0.0
Ch_w: 10.0e-10
h_w: 0.001
alpha: 0.1
Cf: 0.004
g: 9.81
R: 0.49
Ds: 
  - 2.1e-4
  - 1.49e-4 
  - 1.05e-4 
  - 7.43e-5 
  - 4.0e-6
lambda_p: 0.4
r0: 2.0
nu: 1.010e-6
kappa: 0.05
nu_a: 0.75
implicit_num: 100
implicit_threshold: 1.0e-10
C_init: 0.0
gamma: 0.35
la: 0.003
water_entrainment: True
suspension: True
sed_entrainment_func: GP1991exp
no_erosion: True
model: 4eq
salt: True
alpha_4eq: 0.4
karman: 0.4
p: 1.0