grid_param:
  spacing: 50.
  nested_region_xmin: 2000
  nested_region_xmax: 6000
  nested_region_ymin: 9000
  nested_region_ymax: 17000
  one_way_nesting: True
  two_way_nesting: False

boundary_condition:
  top_edge: fixed_value
  bottom_edge: fixed_value
  left_edge: fixed_value
  right_edge: fixed_value

model_param:
  h_init: 0.0
  Ch_w: 10.0e-10
  h_w: 0.001
  alpha: 0.08
  Cf: 0.004
  g: 9.81
  R: 1.65
  Ds: 
    - 1.5e-4 # fine sand
    - 1.0e-4 # very fine sand
    - 2.0e-5 # silt
    - 3.0e-6 # clay
  lambda_p: 0.4
  r0: 2.0
  nu: 1.010e-6
  kappa: 0.05
  nu_a: 0.75
  implicit_num: 500
  implicit_threshold: 1.0e-12
  C_init: 0.0
  gamma: 0.35
  la: 0.003
  water_entrainment: True
  water_detrainment: True
  detrainment_coef: 1.0
  suspension: True
  sed_entrainment_func: GP1991exp
  no_erosion: False
  bedload_transport: False
  model: 4eq
  salt: False
  alpha_4eq: 0.6
  karman: 0.4
  p: 1.0
  flow_type: continuous
  one_way_nesting: True
  two_way_nesting: False
