run_param:
  dirpath: # None
  filename: "run_3000.nc"
  num_runs: 10
  processors: 2
  grain_class_num: 5
  Cmin: 0.0001
  Cmax: 0.005
  Umin: 0.01
  Umax: 0.3
  hmin: 0.01
  hmax: 0.3
  rmin: # None
  rmax: # None
  endmin: 30
  endmax: 180
  saltmin: 0.0001
  saltmax: 0.005
  Cfmin: 0.001
  Cfmax: 0.005
  alpha_4eqmin: 0.1
  alpha_4eqmax: 0.6
  r0min: 1.0
  r0max: 2.0
  repeat: 2
  timelimit: # None
  flow_type: continuous

grid:
  length: 4.5
  width: 1.9
  spacing: 0.05
  slope_outside: 0.1
  slope_inside: 0.1
  slope_basin: 0.05
  slope_basin_break: 3.0
  canyon_basin_break: 3.0
  canyon_center: 0.8
  canyon_half_width: 1.0
  canyon: canyon
  noise: 0.0

flow:
  h_init: 0.0
  Ch_w: 10.0e-10
  h_w: 0.001
  alpha: 0.1
  Cf: 0.004
  g: 9.81
  R: 0.49
  Ds: 
    - 2.1e-4
    - 1.49e-4 
    - 1.05e-4 
    - 7.43e-5 
    - 4.0e-6
  lambda_p: 0.4
  r0: 1.5
  nu: 1.010e-6
  kappa: 0.05
  nu_a: 0.75
  implicit_num: 100
  implicit_threshold: 1.0e-10
  C_init: 0.0
  gamma: 0.35
  la: 0.003
  water_entrainment: True
  suspension: True
  sed_entrainment_func: GP1991exp
  no_erosion: True
  model: 3eq
  salt: True
  alpha_4eq: 0.4
  karman: 0.4
  p: 1.0