run_param:
  dirpath: 
  filename: "run_3000.nc"
  num_runs: 10
  processors: 1
  grain_class_num: 5
  Cmin: 0.0001
  Cmax: 0.005
  Umin: 0.01
  Umax: 0.3
  hmin: 0.01
  hmax: 0.3
  rmin: # None
  rmin: # None
  endmin: 5
  endmax: 5
  saltmin: 0.0001
  saltmax: 0.005
  repeat: 2
  timelimit: # None
  flow_type: continuous

grid:
  length: 4.5
  width: 1.9
  spacing: 0.05
  slope_outside: 0.1
  slope_inside: 0.1
  slope_basin: 0.05
  slope_basin_break: 3.0
  canyon_basin_break: 3.0
  canyon_center: 0.8
  canyon_half_width: 
  canyon: canyon
  noise: 0.0

flow:
  h_init: 0.0
  Ch_w: 10.e-4
  h_w: 0.01
  alpha: 0.4
  Cf: 0.004
  g: 9.81
  R: 0.49
  Ds: 
    - 2.1e-4
    - 1.5e-4 
    - 1.05e-4 
    - 7.4e-5 
    - 4.0e-6
  lambda_p: 0.4
  r0: 1.5
  nu: 1.010e-6
  kappa: 0.01
  nu_a: 0.8
  implicit_num: 100
  implicit_threshold: 1.0e-12
  C_init: 0.0
  gamma: 0.35
  la: 0.003
  water_entrainment: True
  suspension: True
  sed_entrainment_func: "GP1991field"
  no_erosion: True
  model: "3eq"
  salt: True
  alpha_4eq: 0.1
  karman: 0.4